fetch api
Autocv92/exclusive-app pull request #4
Opened 2024-08-29 18:07 UTC by Autocv92

![image](https://github.com/user-attachments/assets/300a78d2-dce8-4269-9fcb-1d4e9bd34960)

2024-08-29 18:10 UTC, deepakscodelab reviewed
Add the screenshot to the PR

2024-08-29 18:12 UTC, Autocv92 commented
![image](https://github.com/user-attachments/assets/eacfff0a-c6f0-496a-a465-e47895493f93)

2024-08-29 18:15 UTC, deepakscodelab submitted a review, later dismissed

2024-08-29 18:29 UTC, deepakscodelab requested changes
Design is not according to mocks

2024-09-06 17:35 UTC, deepakscodelab approved these changes

2024-09-06 17:48 UTC, merged